### ISSUE TITLE
Error connecting to GitHub.com. Please check your connection. 

### ISSUE THREAD

**Issue by ghost** [xchwarze/wifi-pineapple-panel#3]
hey :) im connected to wifi through client mode, and in dashboard and modules i get this error Error connecting to GitHub.com. Please check your connection. hope you can help :) oh im using wifi pineapple nano.

**Comment by xchwarze** [comment]
Hello!
The builds are already quite tested and as the download repository documentation mentions, 99% of the time there is a failure it is due to some user problem.
